### ISSUE TITLE
Mustache Failure

### ISSUE THREAD

**Issue by harikt** [friendsofaura/FOA.Responder_Bundle#1]
Mustache tests fails to set the content on response.

**Comment by harikt** [comment]
Hi @bobthecow, 

Sorry to ping you. I have a test here https://github.com/friendsofaura/FOA.Responder_Bundle/blob/master/tests/integration/src/MustacheResponderTest.php , which is calling via https://github.com/friendsofaura/FOA.Responder_Bundle/blob/master/src/AbstractResponder.php#L93 which calls the https://github.com/friendsofaura/FOA.Responder_Bundle/blob/master/src/MustacheRenderer.php#L13 .

Echoing the from https://github.com/friendsofaura/FOA.Responder_Bundle/blob/master/src/MustacheRenderer.php#L13 shows `Hello Hari` , but not sure why when returned. May be some specific cache or settings ?

Any help is appreciated.

Thank you.

**Comment by bobthecow** [comment]
You closed the issue. I assume this is because you got it sorted out?

**Comment by harikt** [comment]
Yup. Thank you @bobthecow for peeping into this. It was basically a new line character but was unable to figure it was the new line that causing issue. So trimed . Will push soon.
