### ISSUE TITLE
Licence / organization change

### ISSUE THREAD

**Issue by harikt** [friendsofaura/FOA.Responder_Bundle#8]
Hi @nyamsprod , @bobthecow , @rohith-m ,

I am going to move the Renderer to https://github.com/cocoframework .

There is also change in Licence from BSD to MIT .

Let me know if you have any concerns for change in Licence.

Thank you

**Comment by bobthecow** [comment]
License change is fine with me.

**Comment by harikt** [comment]
Thank you @bobthecow for the fast response.

**Comment by nyamsprod** [comment]
License change is fine with me too even thought  I never quite understood the difference between this BSD version and MIT.

**Comment by harikt** [comment]
Thank you @nyamsprod . I just changed to MIT for many people consider MIT . I am also not sure between these though.
